#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the 此刻便是春天 workbench from data-driven sources.

Current scope:
  - Read global config from data/workbench.json (theme + module registry).
  - Load enabled module JSON files from data/modules/.
  - Enrich the reading module via transformers/reading.py.
  - Replace theme tokens in module metadata.
  - Inject the reading module into the workbench HTML.
  - Preserve all other modules (tasks, etc.) exactly as they are.
  - Backup the old workbench and validate the result.

Cleanup rules:
  1. Pre-build cleanup: remove leftover temporary artifacts and old backups.
  2. Post-build cleanup: runs after full validation to remove newly generated
     temporary artifacts such as __pycache__ and .trae-html-share-packages.
  Note: __pycache__ and .trae-html-share-packages are regenerated by Python
  and Trae during execution; they are cleaned on every build.

Usage:
    python build.py
    python build.py --skip-validate
    python build.py --dry-run
"""

import argparse
import importlib
import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
WORKBENCH = ROOT / 'Workbench' / '此刻便是春天.html'
DATA_DIR = ROOT / 'Workbench' / 'data'
MODULES_DIR = DATA_DIR / 'modules'
TRANSFORMERS_DIR = ROOT / 'transformers'
SKILLS_DIR = ROOT / '.trae' / 'skills'

# Paths that must never be removed by cleanup operations, even if a cleanup
# pattern accidentally matches them.
PROTECTED_PATHS = {
    ROOT / '.trae',
    ROOT / '.git',
    ROOT / 'temp',
    ROOT / 'transformers',
    ROOT / 'Workbench',
    ROOT / 'build.py',
    ROOT / '文件说明.md',
    ROOT / '项目约束总览.md',
}

# Directory names that are known temporary artifacts. They may live inside
# protected roots (e.g. __pycache__ under .trae/skills) and are allowed to be
# cleaned up even though their parent directories are protected.
TEMP_DIR_NAMES = {'__pycache__', '.trae-html-share-packages'}

if str(SKILLS_DIR) not in sys.path:
    sys.path.insert(0, str(SKILLS_DIR))
if str(TRANSFORMERS_DIR) not in sys.path:
    sys.path.insert(0, str(TRANSFORMERS_DIR))

from reading_integration import validate_js


def load_workbench_config() -> dict:
    """Load the global workbench configuration."""
    config_path = DATA_DIR / 'workbench.json'
    if not config_path.exists():
        raise FileNotFoundError(f'Workbench config not found: {config_path}')
    return json.loads(config_path.read_text(encoding='utf-8'))


def get_active_tokens(config: dict) -> dict:
    """Return the token map for the active theme."""
    active = config.get('activeTheme', 'light')
    themes = config.get('themes', {})
    if active not in themes:
        raise ValueError(f'Active theme not found: {active}')
    return themes[active].get('tokens', {})


def load_modules(config: dict) -> list[dict]:
    """Load all enabled module data files."""
    modules = []
    for reg in config.get('modules', []):
        if not reg.get('enabled', True):
            print(f'  [skip] disabled module: {reg.get("id")}')
            continue

        module_file = MODULES_DIR / reg['file']
        if not module_file.exists():
            print(f'  [warn] module file not found: {module_file}')
            continue

        data = json.loads(module_file.read_text(encoding='utf-8'))
        data['_registry'] = reg
        modules.append(data)
    return modules


def apply_tokens(obj, tokens: dict):
    """Recursively replace token names with actual color values."""
    if isinstance(obj, dict):
        return {k: apply_tokens(v, tokens) for k, v in obj.items()}
    if isinstance(obj, list):
        return [apply_tokens(v, tokens) for v in obj]
    if isinstance(obj, str) and obj in tokens:
        return tokens[obj]
    return obj


def enrich_module(data: dict) -> dict:
    """Run a module-specific transformer if one exists."""
    module_id = data.get('id')
    transformer_path = TRANSFORMERS_DIR / f'{module_id}.py'
    if not transformer_path.exists():
        return data

    try:
        module = importlib.import_module(module_id)
        enrich = getattr(module, 'enrich_module', None)
        if enrich:
            return enrich(data)
    except Exception as exc:
        print(f'  [warn] transformer failed for {module_id}: {exc}')

    return data


def backup_workbench() -> Path:
    """Create a timestamped backup next to the workbench."""
    suffix = f'.html.bak-{datetime.now():%Y%m%d_%H%M%S}'
    backup = WORKBENCH.with_suffix(suffix)
    backup.write_text(WORKBENCH.read_text(encoding='utf-8'), encoding='utf-8')
    return backup


def _fix_static_colors(html: str) -> str:
    """Replace hardcoded colors with theme-aware CSS variables."""
    html = html.replace(
        '.qt-tag-medium { background: #E0F2FE; color: var(--blue-text); }',
        '.qt-tag-medium { background: var(--blue-soft); color: var(--blue-text); }'
    )
    html = html.replace(
        '.qt-tag-low { background: #D1FAE5; color: #047857; }',
        '.qt-tag-low { background: var(--green-soft); color: var(--green-text); }'
    )
    html = html.replace(
        '.reading-topic {\n      background: #f1f5f9;',
        '.reading-topic {\n      background: var(--bg2);'
    )
    html = html.replace(
        '.reading-notice {\n      background: #fffbeb; border: 1px solid #fde68a;\n      border-radius: 12px; padding: 1rem 1.25rem;\n      margin-bottom: 1.5rem; color: #92400e; font-size: 0.9rem;\n    }',
        '.reading-notice {\n      background: var(--notice-bg); border: 1px solid var(--notice-border);\n      border-radius: 12px; padding: 1rem 1.25rem;\n      margin-bottom: 1.5rem; color: var(--notice-text); font-size: 0.9rem;\n    }'
    )
    return html


def _build_theme_css() -> str:
    """Return CSS for the theme toggle button and topbar actions."""
    return '''\n    .topbar-actions { display: flex; align-items: center; gap: 8px; }\n    .theme-toggle {\n      display: flex; align-items: center; justify-content: center;\n      width: 34px; height: 34px; border-radius: var(--radius-sm);\n      background: transparent; border: 1px solid var(--rule);\n      color: var(--ink); font-size: 1rem; cursor: pointer;\n      transition: background-color 0.2s var(--ease), border-color 0.2s var(--ease);\n    }\n    .theme-toggle:hover { background: var(--bg2); border-color: var(--rule-strong); }\n'''


def _build_theme_script(config: dict) -> str:
    """Build the inline JS that applies and toggles themes."""
    themes = config.get('themes', {})
    default_theme = config.get('activeTheme', 'light')
    themes_js = json.dumps(themes, ensure_ascii=False)
    return f'''\n<script>\n(function() {{\n  const WORKBENCH_THEMES = {themes_js};\n  const DEFAULT_THEME = '{default_theme}';\n\n  function applyWorkbenchTheme(name) {{\n    const theme = WORKBENCH_THEMES[name] || WORKBENCH_THEMES[DEFAULT_THEME];\n    const root = document.documentElement;\n    Object.entries(theme.tokens).forEach(function(entry) {{\n      root.style.setProperty('--' + entry[0], entry[1]);\n    }});\n    try {{ localStorage.setItem('workbench-theme', name); }} catch (e) {{}}\n    const btn = document.getElementById('theme-toggle');\n    if (btn) btn.textContent = (name === 'dark') ? '☀️' : '🌙';\n  }}\n\n  function toggleWorkbenchTheme() {{\n    const current = localStorage.getItem('workbench-theme') || DEFAULT_THEME;\n    applyWorkbenchTheme(current === 'dark' ? 'light' : 'dark');\n  }}\n\n  const saved = localStorage.getItem('workbench-theme') || DEFAULT_THEME;\n  applyWorkbenchTheme(saved);\n\n  window.toggleWorkbenchTheme = toggleWorkbenchTheme;\n  window.applyWorkbenchTheme = applyWorkbenchTheme;\n}})();\n</script>'''


def _inject_theme_system(html: str, config: dict) -> str:
    """Inject theme toggle button, CSS, and switching JS into the HTML (idempotent)."""
    # Add theme toggle CSS if not already present.
    if '.theme-toggle' not in html:
        menu_toggle_rule = '.menu-toggle { display: none; background: none; border: none; font-size: 1.3rem; cursor: pointer; color: var(--ink); }'
        if menu_toggle_rule in html:
            html = html.replace(menu_toggle_rule, menu_toggle_rule + _build_theme_css())
        else:
            print('  [warn] could not find .menu-toggle rule for theme CSS')

    # Add theme toggle button if not already present.
    if 'id="theme-toggle"' not in html:
        old_topbar = '''  <div class="topbar">\n    <div class="brand"><span class="brand-icon">🌸</span><span>此刻便是春天</span></div>\n    <button class="menu-toggle" onclick="toggleSidebar()">☰</button>\n  </div>'''
        new_topbar = '''  <div class="topbar">\n    <div class="brand"><span class="brand-icon">🌸</span><span>此刻便是春天</span></div>\n    <div class="topbar-actions">\n      <button class="theme-toggle" id="theme-toggle" onclick="toggleWorkbenchTheme()" title="切换主题">🌙</button>\n      <button class="menu-toggle" onclick="toggleSidebar()">☰</button>\n    </div>\n  </div>'''
        if old_topbar in html:
            html = html.replace(old_topbar, new_topbar)
        else:
            print('  [warn] could not find topbar marker for theme button')

    # Inject/refresh theme JS before closing head tag.
    script = _build_theme_script(config)
    if 'WORKBENCH_THEMES' in html:
        # Replace existing theme script to keep it in sync with config.
        html = re.sub(
            r'\n+<script>\n\(function\(\) \{.*?const DEFAULT_THEME = [^;]+;.*?window\.applyWorkbenchTheme = applyWorkbenchTheme;\n\}\)\(\);\n</script>',
            script,
            html,
            flags=re.DOTALL,
        )
    else:
        html = html.replace('</head>', script + '\n</head>')
    return html


def _remove_reading_module(html: str) -> str:
    """Remove all readingHtml constants and the reading workspace from HTML."""
    # Remove all readingHtml<year> constants.
    html = re.sub(
        r'\n?\s*const readingHtml\d{4} = `.*?`;',
        '',
        html,
        flags=re.DOTALL,
    )

    # Remove the reading workspace block using brace counting.
    start_marker = "\n      {\n        id: 'read', name: '阅读资料'"
    start = html.find(start_marker)
    if start != -1:
        brace_start = start + len(start_marker) - len("\n      {")
        depth = 1
        pos = brace_start + 1
        while pos < len(html) and depth > 0:
            if html[pos] == '{':
                depth += 1
            elif html[pos] == '}':
                depth -= 1
            pos += 1

        end = pos
        while end < len(html) and html[end] in ' \t':
            end += 1
        if end < len(html) and html[end] == ',':
            end += 1

        html = html[:start] + html[end:]

    return html


def _extract_year(name: str) -> int | None:
    m = re.search(r'(\d{4})年', name)
    return int(m.group(1)) if m else None


def _build_reading_workspace(data: dict) -> tuple[str, str]:
    """Build (constants_js, workspace_js) for the reading module."""
    constants = []
    items = []

    for category in data.get('categories', []):
        cat_name = category.get('name', '')
        cat_icon = category.get('icon', '')
        cat_icon_bg = category.get('iconBg', '')
        cat_items = []

        for item in category.get('items', []):
            year = _extract_year(item['name'])
            if year is None:
                raise ValueError(f'Cannot extract year from reading item: {item["name"]}')

            constants.append(f'    const readingHtml{year} = `{item["readingHtml"]}`;')

            cat_items.append(
                f'''              {{
                code: '{item.get("code", "")}', name: '{item["name"]}', credits: {item.get("credits", 0)},
                type: '{item["type"]}', exam: '{item.get("exam", "")}', stage: '{item.get("stage", "")}', chapters: {item["chapters"]}, done: {item.get("done", 0)},
                current: '{item.get("current", "")}', tasks: {json.dumps(item.get("tasks", []), ensure_ascii=False)}, review: '{item.get("review", "")}',
                readingHtml: readingHtml{year}
              }}'''
            )

        items_joined = ',\n'.join(cat_items)
        items.append(
            f'''          {{
            name: '{cat_name}', icon: '{cat_icon}', iconBg: '{cat_icon_bg}',
            items: [
{items_joined}
            ]
          }}'''
        )

    categories_joined = ',\n'.join(items)
    workspace_js = f'''      {{
        id: '{data["id"]}', name: '{data["name"]}', icon: '{data.get("icon", "")}', iconBg: '{data.get("iconBg", "")}',
        categories: [
{categories_joined}
        ]
      }}'''

    constants_joined = '\n\n'.join(constants)
    return constants_joined + '\n', workspace_js


def _inject_reading_module(html: str, data: dict) -> str:
    """Inject reading constants and workspace into the workbench HTML."""
    constants_js, workspace_js = _build_reading_workspace(data)

    html = re.sub(
        r'\b(const workspaces = \[)',
        constants_js + r'\1',
        html,
        count=1,
    )

    marker_match = re.search(r"\n(    let currentWorkspaceId = '[^']+';)", html)
    if not marker_match:
        raise ValueError('Could not find marker for workspaces array end')

    idx = marker_match.start(1)
    brace_idx = html.rfind('];', 0, idx)
    if brace_idx == -1:
        raise ValueError('Could not find ]; before marker')

    line_start = html.rfind('\n', 0, brace_idx) + 1
    prev_newline = html.rfind('\n', 0, line_start - 1)
    prev_line = html[prev_newline + 1:line_start].rstrip()
    if not prev_line.endswith(','):
        html = (
            html[:prev_newline + 1]
            + prev_line + ',\n'
            + html[line_start:]
        )
        marker_match = re.search(r"\n(    let currentWorkspaceId = '[^']+';)", html)
        if not marker_match:
            raise ValueError('Could not find marker for workspaces array end')
        idx = marker_match.start(1)
        brace_idx = html.rfind('];', 0, idx)
        line_start = html.rfind('\n', 0, brace_idx) + 1

    html = (
        html[:line_start]
        + workspace_js + ',\n'
        + html[line_start:]
    )

    return html


def run_validate() -> None:
    """Run the workbench validation script."""
    validate_script = SKILLS_DIR / 'validate_workbench.py'
    result = subprocess.run(
        [sys.executable, str(validate_script)],
        capture_output=True,
        text=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(result.returncode)


def _is_protected(path: Path) -> bool:
    """Return True if path is a protected root path or a protected subdirectory.

    Protected paths guard core files and directories against wholesale
    deletion. Directories inside a protected root are also protected so that
    a buggy cleanup pattern cannot wipe out core subdirectories such as
    .trae/skills or Workbench/data. Known temporary directories (e.g.
    __pycache__) are still allowed to be cleaned.
    """
    resolved = path.resolve()
    for protected in PROTECTED_PATHS:
        try:
            protected_resolved = protected.resolve()
        except OSError:
            continue

        # Exact match: the protected root itself.
        if resolved == protected_resolved:
            return True

        # Directory inside a protected root.
        if path.is_dir():
            try:
                relative = resolved.relative_to(protected_resolved)
            except ValueError:
                continue
            if relative.parts and not any(
                part in TEMP_DIR_NAMES for part in relative.parts
            ):
                return True

    return False


def _remove_path(path: Path) -> None:
    """Remove a file or directory tree, refusing protected paths."""
    if _is_protected(path):
        raise PermissionError(f'Refuse to remove protected path: {path}')
    if path.is_file():
        path.unlink()
    elif path.is_dir():
        import shutil
        shutil.rmtree(path)


def _cleanup_pycache(root: Path) -> list[Path]:
    """Recursively remove all __pycache__ directories under root."""
    removed = []
    for pycache in root.rglob('__pycache__'):
        if pycache.is_dir():
            _remove_path(pycache)
            removed.append(pycache)
    return removed


def _cleanup_share_packages() -> list[Path]:
    """Remove Trae-generated HTML share packages."""
    removed = []
    share_dir = ROOT / '.trae-html-share-packages'
    if share_dir.exists():
        _remove_path(share_dir)
        removed.append(share_dir)
    return removed


def _cleanup_old_backups(directory: Path, pattern: str, keep: int = 3) -> list[Path]:
    """Keep the most recent backup files matching pattern, remove the rest."""
    removed = []
    backups = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    for old in backups[keep:]:
        _remove_path(old)
        removed.append(old)
    return removed


def _cleanup_empty_root_dirs() -> list[Path]:
    """Remove empty directories directly under ROOT (excluding core folders)."""
    removed = []
    keep = {'build.py', '.trae', '.git', 'temp', 'transformers', 'Workbench', '文件说明.md'}
    for item in ROOT.iterdir():
        if item.is_dir() and item.name not in keep:
            try:
                # list any content recursively
                contents = list(item.rglob('*'))
                if not contents:
                    _remove_path(item)
                    removed.append(item)
            except PermissionError:
                pass
    return removed


def cleanup_artifacts(dry_run: bool = False) -> dict[str, list[Path]]:
    """Clean up known by-products and intermediate files.

    Returns a mapping from category to list of paths that were (or would be) removed.
    """
    results: dict[str, list[Path]] = {}

    actions = [
        ('pycache', _cleanup_pycache, [ROOT]),
        ('share-packages', _cleanup_share_packages, []),
        ('empty-root-dirs', _cleanup_empty_root_dirs, []),
        ('workbench-backups', _cleanup_old_backups, [ROOT / 'Workbench', '此刻便是春天.html.bak-*']),
    ]

    for name, func, args in actions:
        if dry_run:
            # For dry-run, collect targets without deleting.
            targets: list[Path] = []
            if name == 'pycache':
                targets = [p for p in ROOT.rglob('__pycache__') if p.is_dir()]
            elif name == 'share-packages':
                targets = [p for p in [ROOT / '.trae-html-share-packages'] if p.exists()]
            elif name == 'empty-root-dirs':
                keep = {'build.py', '.trae', '.git', 'temp', 'transformers', 'Workbench', '文件说明.md'}
                targets = [p for p in ROOT.iterdir() if p.is_dir() and p.name not in keep and not list(p.rglob('*'))]
            elif name == 'workbench-backups':
                targets = sorted((ROOT / 'Workbench').glob('此刻便是春天.html.bak-*'), key=lambda p: p.stat().st_mtime, reverse=True)[3:]
            results[name] = targets
        else:
            results[name] = func(*args)

    return results


def build() -> Path:
    """Run the full build process."""
    print('Loading workbench config...')
    config = load_workbench_config()
    tokens = get_active_tokens(config)
    print(f'  active theme: {config.get("activeTheme")}')

    print('Loading modules...')
    modules = load_modules(config)
    for m in modules:
        print(f'  loaded: {m.get("id")}')

    print('Enriching modules...')
    enriched_modules = {}
    for m in modules:
        mid = m.get('id')
        enriched = enrich_module(m)
        enriched = apply_tokens(enriched, tokens)
        enriched_modules[mid] = enriched

    print('Backing up workbench...')
    backup = backup_workbench()
    print(f'  backup: {backup}')

    print('Reading workbench...')
    html = WORKBENCH.read_text(encoding='utf-8')

    print('Fixing static colors...')
    html = _fix_static_colors(html)

    print('Injecting theme system...')
    html = _inject_theme_system(html, config)

    print('Removing old reading module...')
    html = _remove_reading_module(html)

    if 'read' in enriched_modules:
        print('Injecting new reading module...')
        html = _inject_reading_module(html, enriched_modules['read'])
    else:
        print('  [skip] reading module not enabled or missing')

    print('Writing workbench...')
    WORKBENCH.write_text(html, encoding='utf-8')

    print('Validating JS syntax...')
    validate_js(html)
    print('  JS syntax OK')

    return backup


def _report_cleaned(cleaned: dict[str, list[Path]], dry_run: bool) -> int:
    """Print cleanup results and return the number of artifacts."""
    label = 'would remove' if dry_run else 'removed'
    action = 'would be removed' if dry_run else 'removed'
    total = 0
    for category, paths in cleaned.items():
        if paths:
            print(f'  [{label}] {category}:')
            for p in paths:
                print(f'    [{datetime.now():%Y-%m-%d %H:%M:%S}] - {p.relative_to(ROOT)}')
            total += len(paths)
    if total == 0:
        print('  nothing to clean')
    else:
        print(f'  {total} artifact(s) {action}')
    return total


def main() -> int:
    parser = argparse.ArgumentParser(description='Build the 此刻便是春天 workbench.')
    parser.add_argument('--skip-validate', action='store_true', help='Skip running validate_workbench.py')
    parser.add_argument('--dry-run', action='store_true', help='Report artifacts to clean without building or deleting')
    args = parser.parse_args()

    if args.dry_run:
        print('Dry-run: scanning for artifacts to clean (no build, no delete)...')
        _report_cleaned(cleanup_artifacts(dry_run=True), dry_run=True)
        return 0

    print('Pre-build cleanup...')
    _report_cleaned(cleanup_artifacts(dry_run=False), dry_run=False)

    build()

    if not args.skip_validate:
        print('Running full validation...')
        run_validate()
        print('Validation passed.')

    print('Post-build cleanup...')
    _report_cleaned(cleanup_artifacts(dry_run=False), dry_run=False)

    if not args.skip_validate:
        print('Build and validation passed.')
    else:
        print('Build complete (validation skipped).')

    return 0


if __name__ == '__main__':
    sys.exit(main())
