#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the 此刻便是春天 workbench from data-driven sources.

Current scope:
  - Read global config from data/workbench.json (theme + module registry).
  - Load enabled module JSON files from data/modules/.
  - Enrich the reading module via transformers/reading.py.
  - Replace theme tokens in module metadata.
  - Compile shared SASS (_root/_base/_components) to styles/shared/*.css.
  - Compile styles/main.scss into CSS and inject it into the HTML template.
  - Render the workbench HTML from templates/workbench.html.
  - Backup the old workbench and validate the result.

Cleanup rules:
  1. Pre-build cleanup: remove leftover temporary artifacts and old backups.
  2. Post-build cleanup: runs after full validation to remove newly generated
     temporary artifacts such as __pycache__ and .trae-html-share-packages.
  Note: __pycache__ and .trae-html-share-packages are regenerated by Python
  and Trae during execution; they are cleaned on every build.

Usage:
    python build.py
    python build.py --skip-validate
    python build.py --dry-run
"""

import argparse
import importlib
import json
import re
import subprocess
import sys
import webbrowser
from datetime import datetime
from pathlib import Path
from typing import Optional

# 项目根目录与关键路径定义
ROOT = Path(__file__).resolve().parent
WORKBENCH = ROOT / 'Workbench' / '此刻便是春天.html'
DATA_DIR = ROOT / 'data'
MODULES_DIR = DATA_DIR / 'modules'
TRANSFORMERS_DIR = ROOT / 'transformers'
TEMPLATES_DIR = ROOT / 'templates'
TEMPLATE = TEMPLATES_DIR / 'workbench.html'
STYLES_DIR = ROOT / 'styles'
MAIN_SCSS = STYLES_DIR / 'main.scss'
VARIABLES_SCSS = STYLES_DIR / '_variables.scss'
SHARED_DIR = STYLES_DIR / 'shared'
# 共享 SASS → CSS 编译映射：工作台外壳与内容页面共用的样式产物
SHARED_SCSS_SOURCES = [
    ('_root.scss', 'base-vars.css'),
    ('_base.scss', 'base.css'),
    ('_components.scss', 'components.css'),
]
SKILLS_DIR = ROOT / '.trae' / 'skills'

try:
    import sass
except ImportError as exc:
    # libsass 未安装时给出明确提示，避免后续编译失败信息晦涩
    raise ImportError(
        'SASS compilation requires the "libsass" package. '
        'Install it with: pip install libsass'
    ) from exc

# ---------------------------------------------------------------------------
# Cleanup configuration
# ---------------------------------------------------------------------------
# Centralized cleanup rules. Use glob-friendly patterns so the rules stay
# stable when tool versions change directory names.
CLEANUP_CONFIG = {
    # 即使清理规则匹配到这些路径，也绝不允许删除核心目录/文件
    'protected_paths': {
        ROOT / '.trae',
        ROOT / '.git',
        ROOT / 'temp',
        ROOT / 'transformers',
        ROOT / 'data',
        ROOT / 'Workbench',
        ROOT / 'templates',
        ROOT / 'styles',
        ROOT / 'build.py',
        ROOT / '文件说明.md',
        ROOT / '项目约束总览.md',
    },
    # 临时目录名通配规则；即使位于受保护根目录下也可清理
    'temp_dir_patterns': {'__pycache__', '.trae-html-share-*'},
    # 根目录下允许保留的空目录白名单
    'empty_root_keep': {
        'build.py', '.trae', '.git', 'temp', 'transformers', 'data',
        'templates', 'styles', 'Workbench', '文件说明.md',
    },
    # 备份保留规则：保留最近 keep 个备份
    'backup_rules': [
        {
            'directory': ROOT / 'Workbench',
            'pattern': '此刻便是春天.html.bak-*',
            'keep': 3,
        },
    ],
}


# ---------------------------------------------------------------------------
# Theme configuration
# ---------------------------------------------------------------------------
# Base tokens are loaded from styles/_variables.scss so that SASS remains the
# single source of truth for the default (light) theme. workbench.json then
# only needs to declare the *differences* for alternate themes (e.g. dark).
TOKEN_OVERRIDES: dict[str, str] = {}

# 主题变量白名单：仅从这些 SCSS 变量中提取默认值并暴露给模块 JSON / 运行时 JS
THEME_TOKEN_NAMES = {
    'bg', 'surface', 'sidebar', 'bg2', 'ink', 'muted', 'light',
    'rule', 'rule-strong',
    'accent-purple', 'purple-soft', 'purple-text',
    'accent-blue', 'blue-soft', 'blue-text',
    'accent-coral', 'coral-soft', 'coral-text',
    'accent-green', 'green-soft', 'green-text',
    'accent-cyan', 'accent-yellow', 'accent-orange',
    'notice-bg', 'notice-border', 'notice-text',
    'reading-warm',
}

# JSON 中字符串值可能被主题 token 名占用的字段；仅在白名单字段中执行替换
TOKEN_FIELDS = {
    'bg', 'surface', 'sidebar', 'bg2', 'ink', 'muted', 'light',
    'rule', 'rule-strong', 'iconBg',
    'accent-purple', 'purple-soft', 'purple-text',
    'accent-blue', 'blue-soft', 'blue-text',
    'accent-coral', 'coral-soft', 'coral-text',
    'accent-green', 'green-soft', 'green-text',
    'accent-cyan', 'accent-yellow', 'accent-orange',
    'notice-bg', 'notice-border', 'notice-text',
    'reading-warm',
}


def _load_base_tokens_from_scss() -> dict[str, str]:
    """Parse simple color variables from styles/_variables.scss.

    Only variables whose names appear in THEME_TOKEN_NAMES and whose values are
    scalar colors (hex, rgb, rgba, hsl, hsla) are treated as theme tokens.
    Variables that reference other variables (e.g. $brand: $accent-blue) are
    skipped because they are already expressed as CSS aliases in _root.scss.
    """
    if not VARIABLES_SCSS.exists():
        raise FileNotFoundError(f'SCSS variables file not found: {VARIABLES_SCSS}')

    text = VARIABLES_SCSS.read_text(encoding='utf-8')
    tokens: dict[str, str] = {}
    # 匹配形如 $bg: #F0F9FF; 或 $bg: #F0F9FF !default; 的变量定义
    for match in re.finditer(r'^\s*\$(\w[-\w]*):\s*([^;!]+)(?:\s*!default)?;', text, re.MULTILINE):
        name = match.group(1)
        if name not in THEME_TOKEN_NAMES:
            continue
        value = match.group(2).strip()
        # 跳过引用其他变量的派生别名
        if value.startswith('$'):
            continue
        # 仅保留形似颜色的值
        if re.match(r'^(#[0-9a-fA-F]{3,8}|rgba?\(|hsla?\()', value):
            tokens[name] = value

    # 校验白名单中的 token 是否全部存在且有效
    missing = THEME_TOKEN_NAMES - set(tokens)
    if missing:
        raise ValueError(
            f'The following theme tokens are declared in THEME_TOKEN_NAMES '
            f'but missing or invalid in {VARIABLES_SCSS}: {sorted(missing)}'
        )
    return tokens

# 确保 skills 与 transformers 目录可被 import
if str(SKILLS_DIR) not in sys.path:
    sys.path.insert(0, str(SKILLS_DIR))
if str(TRANSFORMERS_DIR) not in sys.path:
    sys.path.insert(0, str(TRANSFORMERS_DIR))

from reading_integration import validate_js, build_reading_html, count_sections


def load_workbench_config() -> dict:
    """Load the global workbench configuration."""
    config_path = DATA_DIR / 'workbench.json'
    if not config_path.exists():
        raise FileNotFoundError(f'Workbench config not found: {config_path}')
    return json.loads(config_path.read_text(encoding='utf-8'))


def get_active_tokens(config: dict) -> dict:
    """Return the merged token map for the active theme.

    SASS variables in styles/_variables.scss are the single source of truth for
    the default (light) theme. workbench.json themes only declare overrides for
    alternate themes (e.g. dark). This function merges base tokens with the
    active theme's overrides so module data always receives complete color
    values.
    """
    active = config.get('activeTheme', 'light')
    themes = config.get('themes', {})
    if active not in themes:
        raise ValueError(f'Active theme not found: {active}')

    # 基础 token 与当前主题覆盖值合并，覆盖值优先级更高
    base_tokens = _load_base_tokens_from_scss()
    overrides = themes[active].get('tokens', {})
    merged = {**base_tokens, **overrides}
    return merged


def load_modules(config: dict) -> list[dict]:
    """Load all enabled module data files."""
    modules = []
    for reg in config.get('modules', []):
        # 跳过显式禁用的模块
        if not reg.get('enabled', True):
            print(f'  [skip] disabled module: {reg.get("id")}')
            continue

        module_file = MODULES_DIR / reg['file']
        if not module_file.exists():
            print(f'  [warn] module file not found: {module_file}')
            continue

        data = json.loads(module_file.read_text(encoding='utf-8'))
        data['_registry'] = reg
        modules.append(data)
    return modules


def apply_tokens(obj, tokens: dict, field_name: str = ''):
    """Recursively replace token names with actual color values.

    Replacement only happens for field names listed in TOKEN_FIELDS. This
    avoids accidentally replacing ordinary text (e.g. item names, review
    content) that happens to match a token name.
    """
    if isinstance(obj, dict):
        return {k: apply_tokens(v, tokens, k) for k, v in obj.items()}
    if isinstance(obj, list):
        return [apply_tokens(v, tokens, field_name) for v in obj]
    # 仅当字段在白名单且字符串恰好等于某个 token 名时才替换
    if isinstance(obj, str) and field_name in TOKEN_FIELDS and obj in tokens:
        return tokens[obj]
    return obj


def enrich_module(data: dict) -> dict:
    """Run a module-specific transformer if one exists."""
    module_id = data.get('id')
    transformer_path = TRANSFORMERS_DIR / f'{module_id}.py'
    if not transformer_path.exists():
        return data

    try:
        # 动态导入 transformers/<module_id>.py
        module = importlib.import_module(module_id)
        enrich = getattr(module, 'enrich_module', None)
        if enrich:
            return enrich(data)
    except Exception as exc:
        print(f'  [warn] transformer failed for {module_id}: {exc}')

    return data


def backup_workbench() -> Path:
    """Create a timestamped backup next to the workbench."""
    suffix = f'.html.bak-{datetime.now():%Y%m%d_%H%M%S}'
    backup = WORKBENCH.with_suffix(suffix)
    backup.write_text(WORKBENCH.read_text(encoding='utf-8'), encoding='utf-8')
    return backup


def _build_theme_script(config: dict) -> str:
    """Build the inline JS that applies and toggles themes.

    主题颜色定义在 _root.scss 的 [data-theme="xxx"] CSS 规则中，
    本脚本只负责设置 data-theme 属性并循环切换，无需内联 token。
    """
    default_theme = config.get('activeTheme', 'light')
    return f'''<script>
(function() {{
  const THEME_ORDER = ['light', 'dark', 'warm', 'nature', 'rose'];
  const THEME_ICONS = {{'light':'🌤️','dark':'🌙','warm':'☀️','nature':'🌿','rose':'🌹'}};
  const DEFAULT_THEME = '{default_theme}';

  function applyWorkbenchTheme(name) {{
    var root = document.documentElement;
    root.setAttribute('data-theme', name);
    try {{ localStorage.setItem('workbench-theme', name); }} catch (e) {{}}
    var btn = document.getElementById('theme-toggle');
    if (btn) btn.textContent = THEME_ICONS[name] || '🌙';
    // 同步主题到所有 iframe 内的内容页面
    document.querySelectorAll('iframe').forEach(function(iframe) {{
      try {{
        iframe.contentWindow.postMessage({{type:'workbench-theme-change',theme:name}}, '*');
      }} catch (e) {{}}
    }});
  }}

  function toggleWorkbenchTheme() {{
    var current = localStorage.getItem('workbench-theme') || DEFAULT_THEME;
    var idx = THEME_ORDER.indexOf(current);
    if (idx === -1) idx = 0;
    applyWorkbenchTheme(THEME_ORDER[(idx + 1) % THEME_ORDER.length]);
  }}

  var saved = localStorage.getItem('workbench-theme') || DEFAULT_THEME;
  applyWorkbenchTheme(saved);

  window.toggleWorkbenchTheme = toggleWorkbenchTheme;
  window.applyWorkbenchTheme = applyWorkbenchTheme;
}})();
</script>'''


def _compile_styles() -> str:
    """Compile styles/main.scss into CSS for inline injection."""
    if not MAIN_SCSS.exists():
        raise FileNotFoundError(f'SCSS entry not found: {MAIN_SCSS}')
    # 使用 libsass 压缩输出，便于内联到 HTML
    # strip BOM — 否则 :root 选择器前会多出 BOM 字符导致浏览器无法识别
    css = sass.compile(filename=str(MAIN_SCSS), output_style='compressed')
    if css and css[0] == '\ufeff':
        css = css[1:]
    return css


def _compile_shared_styles() -> None:
    """编译共享 SASS 文件到 styles/shared/ 目录。

    _root.scss       → base-vars.css   (CSS 变量定义)
    _base.scss       → base.css        (基础重置与布局)
    _components.scss → components.css  (公共组件样式)
    """
    SHARED_DIR.mkdir(parents=True, exist_ok=True)
    for src_name, dst_name in SHARED_SCSS_SOURCES:
        src_path = STYLES_DIR / src_name
        if not src_path.exists():
            raise FileNotFoundError(f'Shared SCSS source not found: {src_path}')
        css = sass.compile(filename=str(src_path), output_style='expanded')
        if css and css[0] == '\ufeff':
            css = css[1:]
        dst_path = SHARED_DIR / dst_name
        dst_path.write_text(css, encoding='utf-8')
        print(f'  compiled: {src_name} → shared/{dst_name}')


def _extract_year(name: str) -> Optional[int]:
    # 从“2026年高考语文...”中提取 4 位年份
    m = re.search(r'(\d{4})年', name)
    return int(m.group(1)) if m else None


def _build_module_workspace(data: dict) -> tuple[str, str]:
    """Build (constants_js, workspace_js) for any module.

    For reading items with a contentSource, the source HTML is transformed and
    injected as a JS constant. For all other items, fields are serialized
    directly so the runtime can render them (e.g. via contentUrl iframe).
    """
    module_id = data.get('id', 'module')
    constants = []
    categories = []
    const_index = 0

    for category in data.get('categories', []):
        cat_name = category.get('name', '')
        cat_icon = category.get('icon', '')
        cat_icon_bg = category.get('iconBg', '')
        cat_items = []

        for item in category.get('items', []):
            enriched = dict(item)

            # reading 类型：内联转换后的 HTML
            if enriched.get('type') == 'reading':
                # 若 transformer 已提供 HTML 字符串则直接使用；否则从 contentSource 读取
                if 'readingHtml' in enriched and isinstance(enriched['readingHtml'], str):
                    transformed = enriched['readingHtml']
                    section_count = enriched.get('chapters', count_sections(transformed))
                elif 'contentSource' in enriched:
                    content_source = enriched.pop('contentSource')
                    source_path = WORKBENCH.parent / content_source
                    if not source_path.exists():
                        raise FileNotFoundError(f'Reading content source not found: {source_path}')
                    source_html = source_path.read_text(encoding='utf-8')
                    section_count = count_sections(source_html)
                    transformed = build_reading_html(source_html)
                else:
                    raise ValueError(f'Reading item must have readingHtml or contentSource: {enriched.get("name")}')

                # 优先按条目名称中的 4 位年份命名常量，保持与验证脚本兼容
                year_match = re.search(r'(\d{4})年', enriched.get('name', ''))
                const_name = f'readingHtml{year_match.group(1)}' if year_match else f'readingHtml{module_id}_{const_index}'
                if not year_match:
                    const_index += 1
                constants.append(f'    const {const_name} = `{transformed}`;')
                enriched['readingHtml'] = const_name
                enriched['chapters'] = section_count
                enriched.setdefault('done', 0)

            # 序列化 item 对象，保留 contentUrl 等运行时字段
            fields = []
            for k, v in enriched.items():
                if isinstance(v, str):
                    fields.append(f"{k}: '{v.replace(chr(39), chr(92)+chr(39))}'")
                elif isinstance(v, (list, dict)):
                    fields.append(f'{k}: {json.dumps(v, ensure_ascii=False)}')
                elif isinstance(v, bool):
                    fields.append(f'{k}: {"true" if v else "false"}')
                elif v is None:
                    fields.append(f'{k}: null')
                else:
                    fields.append(f'{k}: {v}')
            cat_items.append('              {\n                ' + ',\n                '.join(fields) + '\n              }')

        items_joined = ',\n'.join(cat_items) if cat_items else ''
        cat_flat = 'flat: true,' if category.get('flat') else ''
        categories.append(
            f'''          {{
            name: '{cat_name}', icon: '{cat_icon}', iconBg: '{cat_icon_bg}',
            {cat_flat}
            items: [
{items_joined}
            ]
          }}'''
        )

    categories_joined = ',\n'.join(categories)
    workspace_js = f'''      {{
        id: '{data["id"]}', name: '{data["name"]}', icon: '{data.get("icon", "")}', iconBg: '{data.get("iconBg", "")}',
        categories: [
{categories_joined}
        ]
      }}'''

    constants_joined = '\n\n'.join(constants)
    return constants_joined + '\n', workspace_js


# 保留旧函数名作为别名，兼容可能的外部调用
def _build_reading_workspace(data: dict) -> tuple[str, str]:
    return _build_module_workspace(data)


def run_validate() -> None:
    """Run the workbench validation script."""
    validate_script = SKILLS_DIR / 'validate_workbench.py'
    # 调用外部校验脚本 validate_workbench.py
    result = subprocess.run(
        [sys.executable, str(validate_script)],
        capture_output=True,
        text=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(result.returncode)


def _is_protected(path: Path) -> bool:
    """Return True if path is a protected root path or a protected subdirectory.

    Protected paths guard core files and directories against wholesale
    deletion. Directories inside a protected root are also protected so that
    a buggy cleanup pattern cannot wipe out core subdirectories such as
    .trae/skills or data/modules. Known temporary directories matching
    temp_dir_patterns are still allowed to be cleaned.
    """
    resolved = path.resolve()
    protected_paths = CLEANUP_CONFIG['protected_paths']
    temp_patterns = CLEANUP_CONFIG['temp_dir_patterns']

    for protected in protected_paths:
        try:
            protected_resolved = protected.resolve()
        except OSError:
            continue

        # 精确匹配：受保护的根路径本身
        if resolved == protected_resolved:
            return True

        # 受保护根目录下的子目录
        if path.is_dir():
            try:
                relative = resolved.relative_to(protected_resolved)
            except ValueError:
                continue
            # 若路径中包含已知临时目录名，则允许清理；否则视为受保护
            if relative.parts and not any(
                any(part.startswith(pat.rstrip('*')) or part == pat for pat in temp_patterns)
                for part in relative.parts
            ):
                return True

    return False


def _remove_path(path: Path) -> None:
    """Remove a file or directory tree, refusing protected paths."""
    if _is_protected(path):
        raise PermissionError(f'Refuse to remove protected path: {path}')
    if not path.exists():
        # 遍历期间路径可能已被删除（如并发清理或父目录先被移除），容错跳过
        return
    if path.is_file():
        path.unlink()
    elif path.is_dir():
        import shutil
        shutil.rmtree(path)


def _match_dir_name(name: str, patterns: set[str]) -> bool:
    """Return True if a directory name matches any glob-like pattern."""
    for pat in patterns:
        if pat.endswith('*'):
            # 前缀通配：如 .trae-html-share-*
            if name.startswith(pat[:-1]):
                return True
        elif name == pat:
            return True
    return False


def _cleanup_temp_dirs(root: Path) -> list[Path]:
    """Recursively remove directories matching temp_dir_patterns under root."""
    removed = []
    patterns = CLEANUP_CONFIG['temp_dir_patterns']
    for item in root.rglob('*'):
        if item.is_dir() and _match_dir_name(item.name, patterns):
            _remove_path(item)
            removed.append(item)
    return removed


def _cleanup_old_backups(directory: Path, pattern: str, keep: int = 3) -> list[Path]:
    """Keep the most recent backup files matching pattern, remove the rest."""
    removed = []
    # 按修改时间倒序，保留前 keep 个
    backups = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
    for old in backups[keep:]:
        _remove_path(old)
        removed.append(old)
    return removed


def _cleanup_empty_root_dirs() -> list[Path]:
    """Remove empty directories directly under ROOT (excluding core folders)."""
    removed = []
    keep = CLEANUP_CONFIG['empty_root_keep']
    for item in ROOT.iterdir():
        if item.is_dir() and item.name not in keep:
            try:
                # 递归检查是否没有任何内容
                contents = list(item.rglob('*'))
                if not contents:
                    _remove_path(item)
                    removed.append(item)
            except PermissionError:
                pass
    return removed


def cleanup_artifacts(dry_run: bool = False) -> dict[str, list[Path]]:
    """Clean up known by-products and intermediate files.

    Returns a mapping from category to list of paths that were (or would be) removed.
    """
    results: dict[str, list[Path]] = {}

    actions = [
        ('temp-dirs', _cleanup_temp_dirs, [ROOT]),
        ('empty-root-dirs', _cleanup_empty_root_dirs, []),
    ]
    for rule in CLEANUP_CONFIG['backup_rules']:
        actions.append((
            f"backups-{rule['directory'].name}",
            _cleanup_old_backups,
            [rule['directory'], rule['pattern'], rule['keep']],
        ))

    temp_patterns = CLEANUP_CONFIG['temp_dir_patterns']
    empty_keep = CLEANUP_CONFIG['empty_root_keep']

    for name, func, args in actions:
        if dry_run:
            # 仅预览：收集目标但不删除
            targets: list[Path] = []
            if name == 'temp-dirs':
                targets = [
                    p for p in ROOT.rglob('*')
                    if p.is_dir() and _match_dir_name(p.name, temp_patterns)
                ]
            elif name == 'empty-root-dirs':
                targets = [
                    p for p in ROOT.iterdir()
                    if p.is_dir() and p.name not in empty_keep and not list(p.rglob('*'))
                ]
            elif name.startswith('backups-'):
                rule = next(
                    r for r in CLEANUP_CONFIG['backup_rules']
                    if f"backups-{r['directory'].name}" == name
                )
                targets = sorted(
                    rule['directory'].glob(rule['pattern']),
                    key=lambda p: p.stat().st_mtime,
                    reverse=True,
                )[rule['keep']:]
            results[name] = targets
        else:
            results[name] = func(*args)

    return results


def _render_template(template: str, context: dict[str, str]) -> str:
    """Replace {{ key }} placeholders in template with values from context."""
    html = template
    for key, value in context.items():
        placeholder = '{{ ' + key + ' }}'
        html = html.replace(placeholder, value)
    return html


def build() -> Path:
    """Run the full build process."""
    print('Loading workbench config...')
    config = load_workbench_config()
    tokens = get_active_tokens(config)
    print(f'  active theme: {config.get("activeTheme")}')

    print('Loading modules...')
    modules = load_modules(config)
    for m in modules:
        print(f'  loaded: {m.get("id")}')

    print('Enriching modules...')
    enriched_modules = {}
    for m in modules:
        mid = m.get('id')
        enriched = enrich_module(m)
        enriched = apply_tokens(enriched, tokens)
        enriched_modules[mid] = enriched

    print('Backing up workbench...')
    backup = backup_workbench()
    print(f'  backup: {backup}')

    print('Loading template...')
    if not TEMPLATE.exists():
        raise FileNotFoundError(f'Template not found: {TEMPLATE}')
    template = TEMPLATE.read_text(encoding='utf-8')

    print('Rendering modules...')
    reading_constants = ''
    workspace_objs = []
    for m in modules:
        mid = m.get('id')
        constants, ws_js = _build_module_workspace(enriched_modules[mid])
        reading_constants += constants
        workspace_objs.append(ws_js)
    workspaces_array = ',\n'.join(workspace_objs)

    print('Compiling shared styles...')
    _compile_shared_styles()

    print('Compiling styles...')
    styles_css = _compile_styles()

    print('Rendering workbench...')
    context = {
        'styles': styles_css,
        'theme_script': _build_theme_script(config),
        'reading_constants': reading_constants,
        'workspaces_array': workspaces_array,
    }
    html = _render_template(template, context)

    print('Writing workbench...')
    WORKBENCH.write_text(html, encoding='utf-8')

    print('Validating JS syntax...')
    try:
        validate_js(html)
        print('  JS syntax OK')
    except FileNotFoundError:
        print('  [warn] node is not available; skipping JS syntax validation')

    return backup


def _report_cleaned(cleaned: dict[str, list[Path]], dry_run: bool) -> int:
    """Print cleanup results and return the number of artifacts."""
    label = 'would remove' if dry_run else 'removed'
    action = 'would be removed' if dry_run else 'removed'
    total = 0
    for category, paths in cleaned.items():
        if paths:
            print(f'  [{label}] {category}:')
            for p in paths:
                print(f'    [{datetime.now():%Y-%m-%d %H:%M:%S}] - {p.relative_to(ROOT)}')
            total += len(paths)
    if total == 0:
        print('  nothing to clean')
    else:
        print(f'  {total} artifact(s) {action}')
    return total


def _confirm_cleanup(cleaned: dict[str, list[Path]]) -> bool:
    """Print the cleanup list and ask the user for confirmation."""
    total = sum(len(paths) for paths in cleaned.values())
    if total == 0:
        print('Nothing to clean.')
        return True

    print(f'About to remove {total} artifact(s):')
    for category, paths in cleaned.items():
        if not paths:
            continue
        print(f'  [{category}]')
        for p in paths:
            print(f'    - {p.relative_to(ROOT)}')

    while True:
        try:
            answer = input('Proceed with cleanup? [y/N]: ').strip().lower()
        except EOFError:
            print('Non-interactive environment; use --dry-run to preview.')
            return False
        if answer in ('y', 'yes'):
            return True
        if answer in ('n', 'no', ''):
            print('Cleanup cancelled.')
            return False
        print('Please answer y or n.')


def main() -> int:
    parser = argparse.ArgumentParser(description='Build the 此刻便是春天 workbench.')
    parser.add_argument('--skip-validate', action='store_true', help='Skip running validate_workbench.py')
    parser.add_argument('--dry-run', action='store_true', help='Report artifacts to clean without building or deleting')
    parser.add_argument('--confirm', action='store_true', help='Confirm before removing artifacts')
    parser.add_argument('--open', action='store_true', help='Open the generated workbench in the default browser after build')
    args = parser.parse_args()

    if args.dry_run:
        print('Dry-run: scanning for artifacts to clean (no build, no delete)...')
        _report_cleaned(cleanup_artifacts(dry_run=True), dry_run=True)
        return 0

    print('Pre-build cleanup...')
    pre_cleaned = cleanup_artifacts(dry_run=args.confirm)
    if args.confirm and not _confirm_cleanup(pre_cleaned):
        return 0
    if not args.confirm:
        _report_cleaned(pre_cleaned, dry_run=False)

    build()

    if not args.skip_validate:
        print('Running full validation...')
        run_validate()
        print('Validation passed.')

    print('Post-build cleanup...')
    post_cleaned = cleanup_artifacts(dry_run=args.confirm)
    if args.confirm and not _confirm_cleanup(post_cleaned):
        return 0
    if not args.confirm:
        _report_cleaned(post_cleaned, dry_run=False)

    if not args.skip_validate:
        print('Build and validation passed.')
    else:
        print('Build complete (validation skipped).')

    if args.open:
        # 构建校验完成后用默认浏览器打开工作台，方便在模拟器中预览效果
        workbench_url = WORKBENCH.resolve().as_uri()
        print(f'Opening workbench in browser: {workbench_url}')
        webbrowser.open(workbench_url)

    return 0


if __name__ == '__main__':
    sys.exit(main())
